apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
  labels:
    run: sa-pod
spec:
  containers:
  - name: busybox-curl
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/radial/busyboxplus:curl
    command: ['sh','-c','while true; do curl -s --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes/api/v1/namespaces/default/pods; sleep 7; done']


