apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: god-power
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: god-role
subjects:
- kind: ServiceAccount
  name: sa-god-admin
  namespace: default
  
