apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox
    name: busybox
    command: ['env']
  dnsPolicy: ClusterFirst
  restartPolicy: Never
