apiVersion: v1
kind: Pod
metadata:
  name: pod-2-deploy-curl
  labels:
    app: pod-2-deploy-curl
spec:
  containers:
    - name: pod-command-container
      image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx 
      command: ["curl" ]
      args: ["http://ingress-watch-nginx-svc.default.svc.cluster.local", "-i", "-v"]
  restartPolicy: OnFailure

