apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: cm-pod-ssh-wget
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox
    name: busybox
    command: ['/bin/sh', "-c"]
    args: ["while true; do env; sleep 10; done"]
    envFrom:
    - configMapRef:
        name: ssh-wget-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Never
