apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: configmap-pod
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox
    name: busybox
    command: ['env']
    envFrom:
    - configMapRef:
        name: aconfigmap
  dnsPolicy: ClusterFirst
  restartPolicy: Never
