apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-strategy-rollout
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-strategy-rollout
  strategy: 
  template:
    metadata:
      labels:
        app: deployment-strategy-rollout
    spec:
      containers:
      - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx:1.22.1
        name: nginx

