apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: double
  name: double
spec:
  containers:
  - image: busybox
    name: double
  - image: busybox
    name: double
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
