apiVersion: batch/v1
kind: CronJob
metadata:
    name: reporting-cron-job-failures
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 6
      template:
        spec:
          containers:
          - name: reporting-tool
            image: harbor-repo.vmware.com/dockerhub-proxy-cache/devopscube/kubernetes-job-demo:latest
            args: ["100"]
          restartPolicy: Never
      backoffLimit: 3
      activeDeadlineSeconds: 45
      ttlSecondsAfterFinished: 3600
      podFailurePolicy:
        rules:
        - action: Count
          onPodConditions:
          - type: DisruptionTarget
            status: "False"
  

