apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpath-vol
  name: hostpath-vol
spec:
  restartPolicy: OnFailure
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx
    name: hostpath-vol
    command: ['sh','-c','cat /data/data.txt']
    volumeMounts:
    - name: host-data
      mountPath: /data   # Where we mount the volume inside the container
  volumes:
  - name: host-data
    hostPath:
      path: /etc/hostPath/
      type: Directory      # Optional Point to specific directory (must exist on the host)