apiVersion: v1
kind: Service
metadata:
  name: ingress-wear-nginx-svc
  labels:
    run: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ingress-wear-nginx
