apiVersion: v1
kind: Pod
metadata:
  name: init-pod-test
spec:
  containers:
  - name: nginx
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx:stable
  initContainers:
  - name: busybox
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox:stable
    command: ['sh', '-c','sleep 60']

