apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  backoffLimit: 6   # Num Retries of failed POds before marking Job as Failed
  parallelism: 4    # Num of PODs to run in parallel
  completions: 20   # Num PODS Completed to consider the job complete
  template:
    spec:
      containers:
        - name: math-add
          image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
          command: ["expr","3","+","4"]
      restartPolicy: Never
