apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  template:
    spec:
      containers:
        - name: math-add
          image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
          command: ["expr","3","+","4"]
      restartPolicy: Never