apiVersion: v1
kind: Pod
metadata:
  labels:
    run: manual-scheduling
  name: manual-scheduling
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx
    name: manual-scheduling
  nodeName: tanzu-cli-09-tkc-pool-0-6q5bj-b56b6fc54-qpxnb
  restartPolicy: Never
