apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: neb-new-job
spec:
  parallelism: 2
  completions: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: awesome-job
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        args: ["sleep 2 && echo done"]
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox:1.31.0
        name: neb-new-job-container
        resources: {}
      restartPolicy: Never
status: {}
