apiVersion: networking.k8s.io/v1
kind: NetworkPolicy     # From CKAD killercoda https://killercoda.com/killer-shell-ckad
metadata:
  name: np
  namespace: space1
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: space2