apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    tier: web
  name: nginx
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Never
