apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: project-gcc-svc
  name: project-gcc-svc
  namespace: pluto
spec:
  ports:
  - name: 3380-80
    port: 3380
    protocol: TCP
    targetPort: 80
  selector:
    app: project-gcc-svc
  type: ClusterIP
status:
  loadBalancer: {}
