apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath  # Just for Docker Desktop or Minikube usually 'manual'
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  
