apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: secret-volume-nginx
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx
    name: secret-volume-nginx
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: app-secret
    volumeMounts:
    - mountPath: /opt
      name: app-secret-volume
  volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret
