apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: secret-nginx
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx
    name: secret-nginx
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: app-secret
