apiVersion: v1
kind: Service
metadata:
  name: services-nginx-deploy
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    run: nginx
    tier: web