# Service Configuration
# --------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-with-sidecar
  labels:
    run: simple-webapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer