apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
  labels:
    app: webapp
spec:
  containers:
    - name: main-nginx
      image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
    - name: sidecar-busybox
      image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox
      command: ["sh","-c","while true; do cat /var/log/nginx/access.log; sleep 30; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
  volumes:
    - name: shared-logs
      emptyDir: {}
