apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: hostpath # Just for Docker Desktop or Minikube usually 'manual'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
