apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project-earthflower
  name: project-earthflower
  namespace: earth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-earthflower
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-earthflower
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        name: httpd
        resources: {}
        volumeMounts:
        - mountPath: "/tmp/project-data"
          name: earth-project-earthflower-pvc

      volumes:
        - name: earth-project-earthflower-pvc
          persistentVolumeClaim:
            claimName: earth-project-earthflower-pvc

status: {}
