apiVersion: v1
kind: PersistentVolume
metadata:
  name: earth-project-earthflower-pv
  namespace: earth
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Volumes/Data"
