apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: configmap-pod2
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox
    name: busybox
    command: ['env']    
    env:
      - name: COLOR
        valueFrom:
          configMapKeyRef:
            name: aconfigmap
            key: COLOR
  dnsPolicy: ClusterFirst
  restartPolicy: Never

