apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: neb-new-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox:1.31.0
        name: neb-new-job
        resources: {}
      restartPolicy: Never
status: {}
