apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod6
  name: pod6
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - touch /tmp/ready && sleep 1d
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox:1.31.0
    name: pod6
    resources: {}
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 20
      periodSeconds: 15
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
