apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resourcepod
  name: resourcepod
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox
    name: resourcepod
    command: ["/bin/sh","-c"]
    args: ["while true; do ls -ahl; sleep 30; done"]
    resources:
      requests:
        cpu: "100m"
        memory: "36Mi"
      limits:
        cpu: "300m"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
