apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx:alpine
    name: secret-pod
    envFrom:
    - secretRef:
        name: test-secret
    resources: {}
#    volumeMounts:
#    - name: test-secret-volume
#      mountPath: /etc/secret-volume
#      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: test-secret-volume
    secret:
      secretName: test-secret


status: {}
